#! /bin/bash
# This runs the sample for rows access as records.
# For windows, see source of b_rows_as_records.erl
cd ..
make
cd samples
erlc b_rows_as_records.erl
erl -pa ../ebin -s b_rows_as_records run -s init stop -noshell
