#! /bin/bash
# This runs the sample for stored procedures.
# For windows, see source of c_stored_procedure.erl
cd ..
make
cd samples
erlc c_stored_procedure.erl
erl -pa ../ebin -s c_stored_procedure run -s init stop -noshell
